// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DomainName
    {
        /// <summary>
        /// Initializes a new instance of the DomainName class.
        /// </summary>
        public DomainName()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DomainName class.
        /// </summary>
        public DomainName(string primaryDomainName = default(string))
        {
            PrimaryDomainName = primaryDomainName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "primary_domain_name")]
        public string PrimaryDomainName { get; set; }

    }
}
