// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class OrderStatuses
    {
        /// <summary>
        /// Initializes a new instance of the OrderStatuses class.
        /// </summary>
        public OrderStatuses()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderStatuses class.
        /// </summary>
        public OrderStatuses(IList<OrderStatusSetting> statuses = default(IList<OrderStatusSetting>))
        {
            Statuses = statuses;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "statuses")]
        public IList<OrderStatusSetting> Statuses { get; set; }

    }
}
