// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OrderStatusSetting
    {
        /// <summary>
        /// Initializes a new instance of the OrderStatusSetting class.
        /// </summary>
        public OrderStatusSetting()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OrderStatusSetting class.
        /// </summary>
        public OrderStatusSetting(string name = default(string), string colour = default(string), bool? showInQuickStats = default(bool?))
        {
            Name = name;
            Colour = colour;
            ShowInQuickStats = showInQuickStats;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "colour")]
        public string Colour { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "show_in_quick_stats")]
        public bool? ShowInQuickStats { get; set; }

    }
}
