// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PlanRestriction
    {
        /// <summary>
        /// Initializes a new instance of the PlanRestriction class.
        /// </summary>
        public PlanRestriction()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlanRestriction class.
        /// </summary>
        public PlanRestriction(string id = default(string), string errorMessage = default(string), string upgradePlanId = default(string))
        {
            Id = id;
            ErrorMessage = errorMessage;
            UpgradePlanId = upgradePlanId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "error_message")]
        public string ErrorMessage { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upgrade_plan_id")]
        public string UpgradePlanId { get; set; }

    }
}
