// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductImages
    {
        /// <summary>
        /// Initializes a new instance of the ProductImages class.
        /// </summary>
        public ProductImages()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductImages class.
        /// </summary>
        public ProductImages(ProductImage image1 = default(ProductImage), ProductImage image2 = default(ProductImage), ProductImage image3 = default(ProductImage), ProductImage image4 = default(ProductImage), ProductImage image5 = default(ProductImage))
        {
            Image1 = image1;
            Image2 = image2;
            Image3 = image3;
            Image4 = image4;
            Image5 = image5;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image1")]
        public ProductImage Image1 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image2")]
        public ProductImage Image2 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image3")]
        public ProductImage Image3 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image4")]
        public ProductImage Image4 { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "image5")]
        public ProductImage Image5 { get; set; }

    }
}
