// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductVariantStock
    {
        /// <summary>
        /// Initializes a new instance of the ProductVariantStock class.
        /// </summary>
        public ProductVariantStock()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductVariantStock class.
        /// </summary>
        public ProductVariantStock(long? id = default(long?), long? parentProductId = default(long?), long? stock = default(long?))
        {
            Id = id;
            ParentProductId = parentProductId;
            Stock = stock;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parent_product_id")]
        public long? ParentProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stock")]
        public long? Stock { get; set; }

    }
}
