// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class ProductOption
    {
        /// <summary>
        /// Initializes a new instance of the ProductOption class.
        /// </summary>
        public ProductOption()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductOption class.
        /// </summary>
        public ProductOption(string name, long? id = default(long?), long? productId = default(long?), bool? isRequired = default(bool?), string type = default(string), int? size = default(int?), IList<ProductOptionItem> optionItems = default(IList<ProductOptionItem>))
        {
            Id = id;
            ProductId = productId;
            Name = name;
            IsRequired = isRequired;
            Type = type;
            Size = size;
            OptionItems = optionItems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product_id")]
        public long? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_required")]
        public bool? IsRequired { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "option_items")]
        public IList<ProductOptionItem> OptionItems { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Name == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Name");
            }
            if (Size < 1)
            {
                throw new ValidationException(ValidationRules.InclusiveMinimum, "Size", 1);
            }
            if (OptionItems != null)
            {
                foreach (var element in OptionItems)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
