// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductStock
    {
        /// <summary>
        /// Initializes a new instance of the ProductStock class.
        /// </summary>
        public ProductStock()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductStock class.
        /// </summary>
        public ProductStock(long? id = default(long?), long? stock = default(long?), long? totalProductStock = default(long?))
        {
            Id = id;
            Stock = stock;
            TotalProductStock = totalProductStock;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "stock")]
        public long? Stock { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "total_product_stock")]
        public long? TotalProductStock { get; set; }

    }
}
