// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductAttributeItem
    {
        /// <summary>
        /// Initializes a new instance of the ProductAttributeItem class.
        /// </summary>
        public ProductAttributeItem()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductAttributeItem class.
        /// </summary>
        public ProductAttributeItem(long? id = default(long?), string attributeKey = default(string), long? productId = default(long?), string attributeValue = default(string), bool? visible = default(bool?), string ebayAttributeName = default(string), long? orderLocation = default(long?))
        {
            Id = id;
            AttributeKey = attributeKey;
            ProductId = productId;
            AttributeValue = attributeValue;
            Visible = visible;
            EbayAttributeName = ebayAttributeName;
            OrderLocation = orderLocation;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attribute_key")]
        public string AttributeKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product_id")]
        public long? ProductId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attribute_value")]
        public string AttributeValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "visible")]
        public bool? Visible { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ebay_attribute_name")]
        public string EbayAttributeName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "order_location")]
        public long? OrderLocation { get; set; }

    }
}
