// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductImage
    {
        /// <summary>
        /// Initializes a new instance of the ProductImage class.
        /// </summary>
        public ProductImage()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductImage class.
        /// </summary>
        public ProductImage(long? id = default(long?), string local = default(string), string remote = default(string), int? width = default(int?), int? height = default(int?), string location = default(string), System.DateTime? uploadDate = default(System.DateTime?), string sectionType = default(string))
        {
            Id = id;
            Local = local;
            Remote = remote;
            Width = width;
            Height = height;
            Location = location;
            UploadDate = uploadDate;
            SectionType = sectionType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "local")]
        public string Local { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "remote")]
        public string Remote { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public int? Width { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public int? Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public string Location { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upload_date")]
        public System.DateTime? UploadDate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "section_type")]
        public string SectionType { get; set; }

    }
}
