// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductAttribute
    {
        /// <summary>
        /// Initializes a new instance of the ProductAttribute class.
        /// </summary>
        public ProductAttribute()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductAttribute class.
        /// </summary>
        public ProductAttribute(string attributeKey = default(string), string visibleName = default(string), bool? systemAttribute = default(bool?))
        {
            AttributeKey = attributeKey;
            VisibleName = visibleName;
            SystemAttribute = systemAttribute;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attribute_key")]
        public string AttributeKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "visible_name")]
        public string VisibleName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "system_attribute")]
        public bool? SystemAttribute { get; set; }

    }
}
