// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Ekm.Mobile.Services.Dtos
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ProductCategory
    {
        /// <summary>
        /// Initializes a new instance of the ProductCategory class.
        /// </summary>
        public ProductCategory()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ProductCategory class.
        /// </summary>
        public ProductCategory(long? categoryId = default(long?), bool? isCategoryManaged = default(bool?))
        {
            CategoryId = categoryId;
            IsCategoryManaged = isCategoryManaged;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category_id")]
        public long? CategoryId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "is_category_managed")]
        public bool? IsCategoryManaged { get; set; }

    }
}
